# https://stylelint.io/user-guide/rules/list
# https://github.com/stylelint-scss/stylelint-scss#list-of-rules

extends:
  - stylelint-config-standard-scss
  - stylelint-config-css-modules

defaultSeverity: warning

rules:
  # @see https://stylelint.io/user-guide/rules/regex#enforce-a-case
  # snake_case – because of css modules.
  selector-class-pattern: "(^([a-z][a-z0-9]*)(_[a-z0-9]+)*$)"

  # @see https://stylelint.io/user-guide/rules/list/font-family-name-quotes/#options
  font-family-name-quotes: "always-unless-keyword"

  max-line-length:
    - 120
    -
      ignore:
        - comments
      # fonts lists may be quite long
      ignorePattern: "/font\\-family:/"

  at-rule-no-unknown: null
  scss/at-rule-no-unknown: true

  color-hex-length: "long"

  # this rule doesn't make any real help,
  # while exact units may be needed in `calc` formulas
  length-zero-no-unit: null

  # Often we want to group some props manually
  declaration-empty-line-before: null
  custom-property-empty-line-before: null

  # In very rare cases it's needed, disable this rule locally
  declaration-no-important: true

  number-leading-zero: always

  at-rule-empty-line-before:
    - always
    -
      except:
        - "first-nested"
      ignore:
        - "after-comment"
        - "blockless-after-same-name-blockless"

      ignoreAtRules:
        - "if"
        - "else"
        - "each"
        - "for"
        - "return"

  value-list-comma-space-after: always
  value-list-comma-space-before: "never-single-line"
  # This one is quite strange and requires strange-looking codestyle
  value-list-comma-newline-after: null

  block-closing-brace-newline-after:
    - always
    -
      ignoreAtRules:
        - "if"
        - "else"

  comment-whitespace-inside: null
  comment-empty-line-before: null

  # see https://github.com/stylelint-scss/stylelint-scss/blob/HEAD/src/rules/no-global-function-names/README.md
  # It's either not supported by node-sass, or smth else,
  # but following this rule cause compiler to crash with like `SassError: There is no module with the namespace "color"`
  # Also not supported by editors (in particular, WebStorm).
  scss/no-global-function-names: null
