import React from 'react'

import { Page } from 'src/components'

export const Home: React.FC = () => {
  return (
    <Page title="React + TypeScript">
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
    </Page>
  )
}
