import React from 'react'

import { Page } from 'src/components/layouts'
import { Counter } from 'src/features/Counter'

export const Home: React.FC = () => {
  return (
    <Page title="Redux + TypeScript">
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
      <Counter />
    </Page>
  )
}
