import React from 'react'

import { AbcOutlined } from '@mui/icons-material'
import { Button } from '@mui/material'
import * as colors from '@mui/material/colors'
import { createTheme } from '@mui/material/styles'
// @see https://stackoverflow.com/questions/69873793/mui-custom-theme-not-applying
import { ThemeProvider as Emotion10ThemeProvider } from 'emotion-theming'

import { Page } from 'src/components'
import { Counter } from 'src/features/Counter'

const theme = createTheme({
  palette: {
    primary: colors.red,
    secondary: colors.green,
  },
})

function DemoMUI() {
  return (
    <Emotion10ThemeProvider theme={theme}>
      <Button>
        PRIME <AbcOutlined />
      </Button>
      <Button color="secondary">
        SEC <AbcOutlined />
      </Button>
    </Emotion10ThemeProvider>
  )
}

export const Home: React.FC = () => {
  return (
    <Page title="Redux + TypeScript">
      <DemoMUI />
      <p>
        Hello and welcome! :) This app was generated by the Create React App
        template and bootstrapped with Redux, React Router, TypeScript, ESlint,
        Prettier for you. Take a look around ;)
      </p>
      <Counter />
    </Page>
  )
}
